### PR TITLE
Fixed MSI

### PR DESCRIPTION
**Pull request by Welasco**

### CODE REVIEW

**Comment by jongio** [comment]
@Welasco we are moving infra/core modules to AVM, so these changes would need to be made in AVM first and then any trickling changes would be made in azure-dev repo.

The motivation here is to use user-assigned identities throughout the stack, right?

@v-xuto - Can you please have a look at this PR and see if AVM currently supports this?

**Comment by v-xuto** [comment]
> @v-xuto - Can you please have a look at this PR and see if AVM currently supports this?

@jongio We have confirmed, the features in this PR are currently supported by AVM.

**Comment by Welasco** [comment]
Hey @jongio and @v-xuto, We have been using this repo as a sample for the MSI work we are doing. This project is currently not using MSI so we were using as a guidance in how to get it done for customers. My original intention was to send the PR to the fork we have. I'm sorry I sent to this one. But at the end of the day was good because I know we are going to use AVM here.

**Comment by Welasco** [comment]
.

**Pull request closed without merging**
